series: GLM Math
title: Quaternions Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: Builds upon the Improved3D project by introducing Quaternions.
language: C++
tags:
  - Math
extra_resources:
connections:
  - series: GLM Math
    title: Euler Angles Tutorial
